export type MenuCategory = 'cakes' | 'pastries' | 'rusks' | 'biscuits' | 'namkeens' | 'snacks';

export interface MenuItem {
  id: string;
  name: string;
  category: MenuCategory;
  price: null;
  hasPhoto: boolean;
  image: string | null;
  isSeasonal: boolean;
}

export const CATEGORY_LABELS: Record<MenuCategory, string> = {
  cakes: 'Cakes',
  pastries: 'Pastries',
  rusks: 'Rusks',
  biscuits: 'Biscuits',
  namkeens: 'Namkeens',
  snacks: 'Snacks',
};

export const CATEGORY_ICONS: Record<MenuCategory, string> = {
  cakes: 'ðŸŽ‚',
  pastries: 'ðŸ§',
  rusks: 'ðŸž',
  biscuits: 'ðŸª',
  namkeens: 'ðŸ«˜',
  snacks: '🥗',
};

export const menuItems: MenuItem[] = [
  // â”€â”€â”€ CAKES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: 'almond-fruit-cake', name: 'Almond Fruit Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'black-forest-cake', name: 'Black Forest Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'butterscotch-cake', name: 'Butterscotch Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'fresh-fruit-cake', name: 'Fresh Fruit Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'cheesecake', name: 'Cheesecake (Blueberry, Strawberry)', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'pineapple-cake', name: 'Pineapple Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'special-mango-cake', name: 'Special Mango Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: true },
  { id: 'special-blueberry-cake', name: 'Special Blueberry Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chocolate-cake', name: 'Chocolate Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'choco-chips-cake', name: 'Choco Chips Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chocolate-marble-cake', name: 'Chocolate Marble Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chocolate-oreo-cake', name: 'Chocolate Oreo Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'special-truffle-cake', name: 'Special Truffle Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'white-forest-cake', name: 'White Forest Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'mud-cake', name: 'Mud Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'soft-truffle-cake', name: 'Soft Truffle Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'german-black-forest-cake', name: 'German Black Forest Cake', category: 'cakes', price: null, hasPhoto: false, image: null, isSeasonal: false },
  // â”€â”€â”€ PASTRIES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: 'eggless-pineapple-pudding', name: 'Eggless Pineapple Pudding', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-mango-pastry', name: 'Eggless Mango Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-mud-pastry', name: 'Eggless Mud Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-white-forest-pastry', name: 'Eggless White Forest Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-pineapple-pastry', name: 'Eggless Pineapple Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eclairs-pastry', name: 'Eclairs Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-dark-fantasy-pastry', name: 'Eggless Dark Fantasy Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-strawberry-pastry', name: 'Eggless Strawberry Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chocolate-truffle-pastry', name: 'Chocolate Truffle Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-black-forest-pudding', name: 'Eggless Black Forest Pudding', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-chocolate-pudding', name: 'Eggless Chocolate Pudding', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'black-forest-pastry', name: 'Black Forest Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-butterscotch-pastry', name: 'Eggless Butterscotch Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-choco-chip-pastry', name: 'Eggless Choco Chip Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-choco-marble-pastry', name: 'Eggless Choco Marble Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'oreo-pastry', name: 'Oreo Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'rainbow-pastry', name: 'Rainbow Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'german-black-forest-pastry', name: 'German Black Forest Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'red-velvet-pastry', name: 'Red Velvet Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'cheesecake-pastry', name: 'Cheesecake Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'pudding-jars', name: 'Pudding Jars', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'pineapple-pastry', name: 'Pineapple Pastry', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'special-pineapple-eggless-pastry', name: 'Special Pineapple Pastry (Eggless)', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'special-kulhad-pudding', name: 'Special Kulhad Pudding', category: 'pastries', price: null, hasPhoto: false, image: null, isSeasonal: false },

  // â”€â”€â”€ RUSKS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: 'cake-rusk-eggless', name: 'Cake Rusk Eggless', category: 'rusks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'cake-rusk-egg', name: 'Cake Rusk Egg', category: 'rusks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'suji-rusk', name: 'Suji Rusk', category: 'rusks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'sugar-free-rusk', name: 'Sugar-Free Rusk', category: 'rusks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'atta-rusk', name: 'Atta Rusk', category: 'rusks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'shahi-rusk', name: 'Shahi Rusk', category: 'rusks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'milk-rusk', name: 'Milk Rusk', category: 'rusks', price: null, hasPhoto: false, image: null, isSeasonal: false },

  // â”€â”€â”€ BISCUITS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: 'badam-khatai-biscuit', name: 'Badam Khatai Biscuit', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'besan-khatai', name: 'Besan Khatai', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'kaju-pista', name: 'Kaju Pista', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'elaichi-khatai', name: 'Elaichi Khatai', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'eggless-sada-cookies', name: 'Eggless Sada Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chocolate-marble-biscuits', name: 'Chocolate Marble Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'milk-kaju-cookies', name: 'Milk Kaju Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'pista-khatai', name: 'Pista Khatai', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'namkeen-chameli', name: 'Namkeen Chameli', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'special-besan-biscuits', name: 'Special Besan Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'namkeen-jalebi', name: 'Namkeen Jalebi', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'milk-badam-biscuits', name: 'Milk Badam Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gol-jeera-biscuits', name: 'Gol Jeera Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'choco-chips-cookies', name: 'Choco Chips Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'mango-khatai', name: 'Mango Khatai', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'namkeen-paneer-biscuits', name: 'Namkeen Paneer Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'hyderabadi-cookies', name: 'Hyderabadi Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'atta-cookies', name: 'Atta Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'butter-kaju-biscuit', name: 'Butter Kaju Biscuit', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'dry-fruit-cookies', name: 'Dry Fruit Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'oats-cookies', name: 'Oats Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'sweet-jalebi', name: 'Sweet Jalebi', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'special-kaju-cookies', name: 'Special Kaju Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'jam-pista-cookies', name: 'Jam Pista Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'muffin-eggless', name: 'Muffin Eggless', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'coconut-biscuits-egg', name: 'Coconut Biscuits Egg', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'muffin-egg', name: 'Muffin Egg', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'kaju-pista-sugar-free', name: 'Kaju Pista Sugar-Free', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'atta-sugar-free', name: 'Atta Sugar-Free', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'shahi-badam-cookies', name: 'Shahi Badam Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'plain-besan-biscuits', name: 'Plain Besan Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'special-kaju-biscuits', name: 'Special Kaju Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'coconut-biscuits', name: 'Coconut Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'multi-green-biscuits', name: 'Multi Green Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'ragi-biscuits', name: 'Ragi Biscuits', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'osmania-biscuit', name: 'Osmania Biscuit', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'plain-biscuit', name: 'Biscuit', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'kaju-pista-cookies', name: 'Kaju Pista Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'choco-kaju', name: 'Choco Kaju', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'little-heart-biscuit', name: 'Little Heart Biscuit', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'sada-cookies', name: 'Sada Cookies', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'twione-biscuit', name: 'Twione Biscuit', category: 'biscuits', price: null, hasPhoto: false, image: null, isSeasonal: false },

  // â”€â”€â”€ NAMKEENS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: 'makhana', name: 'Makhana', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'flavour-makhana', name: 'Flavour Makhana', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chana-with-kheel', name: 'Chana with Kheel', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gol-mathi', name: 'Gol Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'mote-sev', name: 'Mote Sev', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'soya-katori', name: 'Soya Katori', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'moongra', name: 'Moongra', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gathiya', name: 'Gathiya', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chivda-mixture', name: 'Chivda Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'bikaneri-bhujiya', name: 'Bikaneri Bhujiya', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'diet-snacks', name: 'Diet Snacks', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'soya-katori-cheese', name: 'Soya Katori Cheese', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'murmura-mixture', name: 'Murmura Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'plain-chana', name: 'Plain Chana', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'banana-chips', name: 'Banana Chips', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'potato-chips', name: 'Potato Chips', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'murukku', name: 'Murukku', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gol-gappa-namkeen', name: 'Gol Gappa', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'phiki-mathri', name: 'Phiki Mathri', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'boondi', name: 'Boondi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'besan-papdi', name: 'Besan Papdi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chivda-mixture-lal-dana', name: 'Chivda Mixture Lal Dana', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'spicy-mixture', name: 'Spicy Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'khatta-meetha', name: 'Khatta Meetha', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chinese-samosa', name: 'Chinese Samosa', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'kanpuri-mixture', name: 'Kanpuri Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'panchratan-mixture', name: 'Panchratan Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'dal-beeji', name: 'Dal Beeji', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'moong-dal', name: 'Moong Dal', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'cornflakes-mixture', name: 'Cornflakes Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'cornflakes', name: 'Cornflakes', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'madrasi-mixture', name: 'Madrasi Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gujarati-sev', name: 'Gujarati Sev', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'tangri', name: 'Tangri', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'aloo-bhujiya', name: 'Aloo Bhujiya', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'disco-papad', name: 'Disco Papad', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'plain-mixture', name: 'Plain Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'zero-number-sev', name: 'Zero Number Sev', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'mirchi-sev', name: 'Mirchi Sev', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'soya-chips', name: 'Soya Chips', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'soya-stick', name: 'Soya Stick', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chana-jor', name: 'Chana Jor', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'cocktail-chana', name: 'Cocktail Chana', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'hara-moong', name: 'Hara Moong', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gud-chana', name: 'Gud Chana', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'diet-bajra', name: 'Diet Bajra', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'diet-jowar', name: 'Diet Jowar', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'kadi-patta-chivda', name: 'Kadi Patta Chivda', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'hara-matar', name: 'Hara Matar', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'butter-chakli', name: 'Butter Chakli', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'bombay-chakli', name: 'Bombay Chakli', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'diet-wheat', name: 'Diet Wheat', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'diet-soybean', name: 'Diet Soybean', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'multigrain-mixture', name: 'Multigrain Mixture', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'cheese-ball', name: 'Cheese Ball', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'shakkarpara', name: 'Shakkarpara', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gudpara', name: 'Gudpara', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'milk-mathi', name: 'Milk Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'khajuri-mathi', name: 'Khajuri Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'dabba-mathi', name: 'Dabba Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'tikoni-mathi', name: 'Tikoni Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'satrangi-mathi', name: 'Satrangi Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'achari-mathi', name: 'Achari Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gol-mathi-2', name: 'Gol Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'masala-kaju', name: 'Masala Kaju', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'masala-karela', name: 'Masala Karela', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'masala-chandni', name: 'Masala Chandni', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'papdi', name: 'Papdi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'samosa', name: 'Samosa', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'kachori', name: 'Kachori', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'sweet-karela', name: 'Sweet Karela', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'plain-chandni', name: 'Plain Chandni', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'bhakarwadi', name: 'Bhakarwadi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'namakpara', name: 'Namakpara', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'kachori-big', name: 'Kachori Big', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'matar-samosa', name: 'Matar Samosa', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'pyaz-kachori', name: 'Pyaz Kachori', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'bhalla', name: 'Bhalla', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'fafda', name: 'Fafda', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'gol-gappa-2', name: 'Gol Gappa', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'khasta-mathi', name: 'Khasta Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'amritsari-mathi', name: 'Amritsari Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'pudina-mathi', name: 'Pudina Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'phiki-mathi', name: 'Phiki Mathi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'bhaji-box', name: 'Bhaji Box', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'badam-lacha', name: 'Badam Lacha', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chana-dal', name: 'Chana Dal', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'nut-cracker', name: 'Nut Cracker', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'shing-dana', name: 'Shing Dana', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'peanut', name: 'Peanut', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'khakhra', name: 'Khakhra', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'kulcha', name: 'Kulcha', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'petha', name: 'Petha', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'fan', name: 'Fan', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'bada-fan', name: 'Bada Fan', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'marodi', name: 'Marodi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'palak-marodi', name: 'Palak Marodi', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'oregano-puff', name: 'Oregano Puff', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'puff', name: 'Puff', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'soup-stick', name: 'Soup Stick', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'bread-crumb', name: 'Bread Crumb', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chocolate-muffin', name: 'Chocolate Muffin', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'chocolate-cake-eggless', name: 'Chocolate Cake Eggless', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'fruit-cake-egg', name: 'Fruit Cake Egg', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'fruit-cake-eggless', name: 'Fruit Cake Eggless', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'plum-cake', name: 'Plum Cake', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'cheesling', name: 'Cheesling', category: 'namkeens', price: null, hasPhoto: false, image: null, isSeasonal: false },

  // â”€â”€â”€ SNACKS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  { id: 'khandvi', name: 'Khandvi', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'dhokla', name: 'Dhokla', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'veg-burger', name: 'Veg Burger', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'club-sandwich', name: 'Club Sandwich', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'fresh-paneer', name: 'Fresh Paneer', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'veg-pizza-sandwich', name: 'Veg Pizza Sandwich', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'veg-grilled-burger', name: 'Veg Grilled Burger', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'oregano-burger', name: 'Oregano Burger', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'veg-grilled-paneer-kulcha', name: 'Veg Grilled Paneer Kulcha', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'soya-chaap-wrap', name: 'Soya Chaap Wrap', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'pizza', name: 'Pizza', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'mexican-wrap', name: 'Mexican Wrap', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'paneer-dhokla', name: 'Paneer Dhokla', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'aloo-patties', name: 'Aloo Patties', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'paneer-patties', name: 'Paneer Patties', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'mushroom-patties', name: 'Mushroom Patties', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'grilled-sandwich', name: 'Grilled Sandwich', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'garlic-cheese-loaf', name: 'Garlic Cheese Loaf', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'veg-sandwich', name: 'Veg Sandwich', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'paneer-kulcha', name: 'Paneer Kulcha', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
  { id: 'onion-kachori', name: 'Onion Kachori', category: 'snacks', price: null, hasPhoto: false, image: null, isSeasonal: false },
];

