/* ═══════════════════════════════════════════
   GALLERY DATA WITH REAL IMAGES
   ═══════════════════════════════════════════ */

export interface GalleryItem {
  id: number;
  category: string;
  image: string;
  label: string;
  colSpan: number;
  rowSpan: number;
  aspectDesc?: string;
}

export const categories = [
  'All', 'Promotional Posters', 'Cookies & Biscuits', 'Namkeen & Savories', 'Rusks & Puffs', 'Cakes & Pastries', 'Custom Cakes'
];

const brandedBiscuits: GalleryItem[] = [
  {
    id: 1,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/paper-almond-banner.jpg',
    label: 'Paper Almond Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 2,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/choco-crunch-poster.jpg',
    label: 'Choco Crunch Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 3,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/badam-khatai-square.jpg',
    label: 'Badam Khatai Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 4,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/kaju-pista-cookies.jpg',
    label: 'Kaju Pista Cookies Sugar Free',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 5,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/oats-cookies-portrait.jpg',
    label: 'Golden Oats Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 6,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/special-besan-square.jpg',
    label: 'Special Desi Ghee Besan Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 7,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/almond-biscotti-banner.jpg',
    label: 'Almond Cantucci Biscotti',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 8,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/chocolate-marble-poster.jpg',
    label: 'Chocolate Marble Swirl Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 9,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/namkeen-paneer-landscape.jpg',
    label: 'Namkeen Paneer Cumin Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 10,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/gol-jeera-portrait.jpg',
    label: 'Gol Jeera Roasted Cumin Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 11,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/special-kaju-square.jpg',
    label: 'Special Kaju Cashew Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 12,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/elaichi-khatai-poster.jpg',
    label: 'Elaichi Khatai Cardamom Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 13,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/atta-sugar-free-landscape.jpg',
    label: 'Atta Whole Wheat Sugar Free',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 14,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/choker-namkeen-poster.jpg',
    label: 'Choker Namkeen Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 15,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/plain-besan-portrait.jpg',
    label: 'Plain Besan Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 16,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/besan-khatai-banner.jpg',
    label: 'Royal Besan Khatai Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 17,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/jam-pista-poster.jpg',
    label: 'Jam Pista Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 18,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/cashew-khatai-square.jpg',
    label: 'Royal Cashew Khatai Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 19,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/namkeen-jalebi-landscape.jpg',
    label: 'Namkeen Jalebi Swirls',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 20,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/choco-chips-poster.jpg',
    label: 'Choco Chips Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 21,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/coconut-drops-square.jpg',
    label: 'Toasted Coconut Drops',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 22,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/butter-kaju-banner.jpg',
    label: 'Butter Kaju Biscotti',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 23,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/dry-fruits-poster.jpg',
    label: 'Loaded Dry Fruits Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 24,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/jaggery-multigrain-landscape.jpg',
    label: 'Jaggery Multigrain Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 25,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/sada-butter-square.jpg',
    label: 'Sada Butter Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 26,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/atta-cookies-poster.jpg',
    label: 'Crispy Atta Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 27,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/milk-badam-poster.jpg',
    label: 'Milk Badam Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 28,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/shahi-badam-square.jpg',
    label: 'Shahi Badam Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 29,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/milk-kaju-banner.jpg',
    label: 'Milk Kaju Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 30,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/kaju-pista-poster.jpg',
    label: 'Kaju Pista Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 31,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/toasted-coconut-square.jpg',
    label: 'Toasted Coconut Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 32,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/butter-jam-pista-portrait.jpg',
    label: 'Butter Jam Pista Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 33,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/multi-grain-landscape.jpg',
    label: 'Multi Grain Wholesome Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 34,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/jeera-bite-square.jpg',
    label: 'Jeera Bite Savory Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 35,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/chocos-cookies-poster.jpg',
    label: 'Chocos Cookies',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 36,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/sweet-jalebi-landscape.jpg',
    label: 'Sweet Jalebi Butter Swirls',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 37,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/milk-pista-square.jpg',
    label: 'Milk Pista Royal Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 38,
    category: 'Cookies & Biscuits',
    image: '/gallery/biscuits/hyderabadi-fruit-poster.jpg',
    label: 'Hyderabadi Tutti-Frutti Biscuits',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 39,
    category: 'Namkeen & Savories',
    image: '/gallery/sweets/dry-petha-poster.jpg',
    label: 'Agra Dry Petha',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 40,
    category: 'Rusks & Puffs',
    image: '/gallery/rusks/special-shahi-rusk-poster.jpg',
    label: 'Special Shahi Rusk',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 41,
    category: 'Rusks & Puffs',
    image: '/gallery/rusks/atta-rusk-poster.jpg',
    label: 'Whole Wheat Atta Rusk',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 42,
    category: 'Rusks & Puffs',
    image: '/gallery/rusks/milk-rusk-poster.jpg',
    label: 'Classic Crispy Milk Rusk',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 43,
    category: 'Rusks & Puffs',
    image: '/gallery/rusks/ajwain-fan-poster.jpg',
    label: 'Buttery Flaky Ajwain Fan',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 44,
    category: 'Rusks & Puffs',
    image: '/gallery/rusks/chini-kam-rusk-poster.jpg',
    label: 'Less Sugar Chini Kam Rusk',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 45,
    category: 'Rusks & Puffs',
    image: '/gallery/rusks/suji-rusk-poster.jpg',
    label: 'Golden Semolina Suji Rusk',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 46,
    category: 'Rusks & Puffs',
    image: '/gallery/rusks/twisty-puff-poster.jpg',
    label: 'Twisty Puff',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 47,
    category: 'Rusks & Puffs',
    image: '/gallery/rusks/puff-square-poster.jpg',
    label: 'Puff Square',
    colSpan: 1,
    rowSpan: 2,
  },
];

const brandedNamkeen: GalleryItem[] = [
  {
    id: 101,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/bhakarwadi-poster.jpg',
    label: 'Traditional Bhakarwadi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 102,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/dabba-mathi-poster.jpg',
    label: 'Crispy Dabba Mathi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 103,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/gol-mathi-poster.jpg',
    label: 'Traditional Gol Mathi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 104,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/achari-mathi-poster.jpg',
    label: 'Tangy Achari Mathi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 105,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/suji-til-mathi-poster.jpg',
    label: 'Suji Til Mathi Banner',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 106,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/shakarpara-poster.jpg',
    label: 'Shakarpara Sweet Delight',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 107,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/gud-para-poster.jpg',
    label: 'Gud Para Winter Treat',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 108,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/satrangi-mathi-poster.jpg',
    label: 'Satrangi 7-Spice Mathi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 109,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/mini-kachori-poster.jpg',
    label: 'Mini Khasta Kachori',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 110,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/aloo-mathi-poster.jpg',
    label: 'Aloo Mathi Savory Banner',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 111,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/bhaji-box-poster.jpg',
    label: 'Festive Bhaji Box Assortment',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 112,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/milk-mathi-poster.jpg',
    label: 'Traditional Milk Mathi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 113,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/khajuri-mathi-poster.jpg',
    label: 'Khajuri Mathi Classic',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 114,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/methi-mathi-poster.jpg',
    label: 'Methi Mathi Kasuri Flavor',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 115,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/tikoni-mathi-poster.jpg',
    label: 'Flaky Tikoni Mathi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 116,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/papdi-poster.jpg',
    label: 'Crispy Wafer Papdi Banner',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 117,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/masala-chandni-poster.jpg',
    label: 'Spiced Masala Chandni',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 118,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/plain-chandni-poster.jpg',
    label: 'Plain Chandni Namkeen',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 119,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/tikoni-laung-mathi-poster.jpg',
    label: 'Aromatic Tikoni Laung Mathi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 120,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/masala-karela-poster.jpg',
    label: 'Masala Karela Crispy Rolls',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 121,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/sweet-karela-poster.jpg',
    label: 'Sweet Karela Glazed Rolls',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 122,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/namak-para-poster.jpg',
    label: 'Namak Para Ajwain Banner',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 123,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/gujrati-sev-poster.jpg',
    label: 'Authentic Gujrati Sev',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 124,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/bikaneri-bhujiya-poster.jpg',
    label: 'Bikaneri Bhujiya Banner',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 125,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/mirchi-sev-poster.jpg',
    label: 'Spicy Mirchi Sev',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 126,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/madrasi-mixture-poster.jpg',
    label: 'Traditional Madrasi Mixture',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 127,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/moongra-poster.jpg',
    label: 'Crispy Moongra',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 128,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/moong-dal-poster.jpg',
    label: 'Crispy Moong Dal Namkeen',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 129,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/zero-sev-poster.jpg',
    label: 'Fine Zero Sev',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 130,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/banana-chips-poster.jpg',
    label: 'Crispy Banana Chips',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 131,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/aloo-bhujia-poster.jpg',
    label: 'Spicy Aloo Bhujia',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 132,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/hing-mirchi-sev-poster.jpg',
    label: 'Spiced Hing Mirchi Sev',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 133,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/plain-cornflex-poster.jpg',
    label: 'Golden Plain Cornflex',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 134,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/murmura-mixture-poster.jpg',
    label: 'Light Murmura Mixture',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 135,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/cornflakes-mixture-poster.jpg',
    label: 'Royal Cornflakes Mixture',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 136,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/curry-leaf-murmura-poster.jpg',
    label: 'Aromatic Curry Leaf Murmura',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 137,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/chiwda-cornflakes-poster.jpg',
    label: 'Chiwda Cornflakes Mix',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 138,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/besan-masala-papdi-poster.jpg',
    label: 'Spiced Besan Masala Papdi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 139,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/besan-papdi-poster.jpg',
    label: 'Melt-in-Mouth Besan Papdi',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 140,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/soya-katori-masala-poster.jpg',
    label: 'Chatpata Soya Katori Masala',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 141,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/kadi-patta-boondi-poster.jpg',
    label: 'Curry Leaf Boondi Pearls',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 142,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/gathiya-poster.jpg',
    label: 'Authentic Gujarati Gathiya',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 143,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/soya-katori-plain-poster.jpg',
    label: 'Light Soya Katori Plain',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 144,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/mirchi-tangri-poster.jpg',
    label: 'Spicy Mirchi Tangri',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 145,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/classic-boondi-poster.jpg',
    label: 'Classic Besan Boondi',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 146,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/mota-sev-poster.jpg',
    label: 'Crispy Mota Sev',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 147,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/white-chidwa-mix-poster.jpg',
    label: 'Roasted White Chidwa Mix',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 148,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/kanpuri-mixture-dryfruit-poster.jpg',
    label: 'Royal Kanpuri Mixture with Dry Fruit',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 149,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/badam-lacha-poster.jpg',
    label: 'Royal Badam Lachha',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 150,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/khatta-meetha-poster.jpg',
    label: 'Sweet & Tangy Khatta Meetha',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 151,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/yellow-chidwa-mix-poster.jpg',
    label: 'Golden Yellow Chidwa Mix',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 152,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/dal-biji-poster.jpg',
    label: 'Royal Dal Biji Mixture',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 153,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/swadishta-mix-poster.jpg',
    label: 'Signature Swadishta Mix',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 154,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/plain-mixture-poster.jpg',
    label: 'Homestyle Plain Mixture',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 155,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/falahari-mix-meetha-poster.jpg',
    label: 'Sweet Falahari Mix',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 156,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/namkeen-falahari-mix-poster.jpg',
    label: 'Namkeen Falahari Mix',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 157,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/nut-cracker-poster.jpg',
    label: 'Spicy Nut Cracker Peanuts',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 158,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/special-corn-namkeen-poster.jpg',
    label: 'Royal Special Corn Namkeen',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 159,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/panchratan-mix-poster.jpg',
    label: 'Crunchy Panchratan Mix',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 160,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/spicy-mixture-poster.jpg',
    label: 'Authentic Spicy Mixture',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 161,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/peri-peri-makhana-poster.jpg',
    label: 'Roasted Peri Peri Makhana',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 162,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/plain-salted-makhana-poster.jpg',
    label: 'Plain Salted Makhana',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 163,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/masala-banana-chips-poster.jpg',
    label: 'Crispy Masala Banana Chips',
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: 164,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/broccoli-chips-poster.jpg',
    label: 'Crispy Broccoli Chips',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 165,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/mix-veg-chips-poster.jpg',
    label: 'Crispy Mix Veg Chips',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 166,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/multigrain-flakes-poster.jpg',
    label: 'Multigrain & Flakes Mixture',
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: 167,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/mint-pudina-makhana-poster.jpg',
    label: 'Mint Pudina Makhana',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 168,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/diet-millet-mix-poster.jpg',
    label: 'Diet Millet Mixture',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 169,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/tandoori-multigrain-sticks-poster.jpg',
    label: 'Tandoori Multigrain Sticks',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 170,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/rajma-chips-poster.jpg',
    label: 'Spiced Rajma Chips',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 171,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/diet-jhalmuri-poster.jpg',
    label: 'Diet Jhal Muri',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 172,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/beetroot-chips-poster.jpg',
    label: 'Crispy Beetroot Chips',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 173,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/black-pepper-makhana-poster.jpg',
    label: 'Black Pepper Makhana',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 174,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/salsa-multigrain-sticks-poster.jpg',
    label: 'Salsa Multigrain Sticks',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 175,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/masala-kaju-poster.jpg',
    label: 'Royal Masala Kaju',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 176,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/mini-samosa-poster.jpg',
    label: 'Crispy Mini Samosa',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 177,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/phool-mathi-poster.jpg',
    label: 'Crispy Layered Phool Mathi',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 178,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/fafda-poster.jpg',
    label: 'Gujarati Fafda',
    colSpan: 1,
    rowSpan: 2,
  },
  {
    id: 179,
    category: 'Namkeen & Savories',
    image: '/gallery/namkeen/palak-marori-poster.jpg',
    label: 'Crispy Palak Marori',
    colSpan: 1,
    rowSpan: 2,
  },
];

const brandedCakes: GalleryItem[] = [
  {
    id: 1000 + 1,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cheesecake-1.jpg',
    label: 'Signature Cheesecake 1 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 2,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-2.jpg',
    label: 'Signature Cake 2 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 3,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-3.jpg',
    label: 'Signature Cake 3 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 4,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-4.jpg',
    label: 'Signature Cake 4 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 1000 + 5,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-5.jpg',
    label: 'Signature Cake 5 (16:9 Banner)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '16:9 Banner',
  },
  {
    id: 1000 + 6,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-6.jpg',
    label: 'Signature Cake 6 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 7,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-7.jpg',
    label: 'Signature Cake 7 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 8,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-8.jpg',
    label: 'Signature Cake 8 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 1000 + 9,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-9.jpg',
    label: 'Signature Cake 9 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 10,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-10.jpg',
    label: 'Signature Cake 10 (16:9 Banner)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '16:9 Banner',
  },
  {
    id: 1000 + 11,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-11.jpg',
    label: 'Signature Cake 11 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 12,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-12.jpg',
    label: 'Signature Cake 12 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 13,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-13.jpg',
    label: 'Signature Cake 13 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 14,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-14.jpg',
    label: 'Signature Cake 14 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 15,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-15.jpg',
    label: 'Premium Pastry 15 (16:9 Banner)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '16:9 Banner',
  },
  {
    id: 1000 + 16,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-16.jpg',
    label: 'Signature Cake 16 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 1000 + 17,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-17.jpg',
    label: 'Signature Cake 17 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 18,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-18.jpg',
    label: 'Premium Pastry 18 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 19,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-19.jpg',
    label: 'Signature Cake 19 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 20,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-20.jpg',
    label: 'Premium Pastry 20 (16:9 Banner)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '16:9 Banner',
  },
  {
    id: 1000 + 21,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-21.jpg',
    label: 'Signature Cake 21 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 22,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-22.jpg',
    label: 'Premium Pastry 22 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 23,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-23.jpg',
    label: 'Premium Pastry 23 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 24,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-24.jpg',
    label: 'Premium Pastry 24 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 25,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-25.jpg',
    label: 'Signature Cake 25 (16:9 Banner)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '16:9 Banner',
  },
  {
    id: 1000 + 26,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-26.jpg',
    label: 'Premium Pastry 26 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 27,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-27.jpg',
    label: 'Premium Pastry 27 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 28,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-28.jpg',
    label: 'Signature Cake 28 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 1000 + 29,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-29.jpg',
    label: 'Premium Pastry 29 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 30,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cheesecake-30.jpg',
    label: 'Signature Cheesecake 30 (16:9 Banner)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '16:9 Banner',
  },
  {
    id: 1000 + 31,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-31.jpg',
    label: 'Premium Pastry 31 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 32,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cheesecake-32.jpg',
    label: 'Signature Cheesecake 32 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 1000 + 33,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-33.jpg',
    label: 'Premium Pastry 33 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 34,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-34.jpg',
    label: 'Signature Cake 34 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 35,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-35.jpg',
    label: 'Signature Cake 35 (16:9 Banner)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '16:9 Banner',
  },
  {
    id: 1000 + 36,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-36.jpg',
    label: 'Signature Cake 36 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 37,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-37.jpg',
    label: 'Signature Cake 37 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 38,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-38.jpg',
    label: 'Signature Cake 38 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 39,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-39.jpg',
    label: 'Signature Cake 39 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 1000 + 40,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-cake-40.jpg',
    label: 'Signature Cake 40 (16:9 Banner)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '16:9 Banner',
  },
  {
    id: 1000 + 41,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-41.jpg',
    label: 'Premium Pastry 41 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 1000 + 42,
    category: 'Cakes & Pastries',
    image: '/gallery/cakes/premium-pastry-42.jpg',
    label: 'Premium Pastry 42 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
];


const brandedCustomCakes: GalleryItem[] = [
  {
    id: 2000 + 1,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-1.jpg',
    label: 'Custom Cake 1 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 2,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-2.jpg',
    label: 'Custom Cake 2 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 3,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-3.jpg',
    label: 'Custom Cake 3 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 2000 + 4,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-4.jpg',
    label: 'Custom Cake 4 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 2000 + 5,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-5.jpg',
    label: 'Custom Cake 5 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 6,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-6.jpg',
    label: 'Custom Cake 6 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 2000 + 7,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-7.jpg',
    label: 'Custom Cake 7 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 8,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-8.jpg',
    label: 'Custom Cake 8 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 2000 + 9,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-9.jpg',
    label: 'Custom Cake 9 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 2000 + 10,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-10.jpg',
    label: 'Custom Cake 10 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 11,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-11.jpg',
    label: 'Custom Cake 11 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 12,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-12.jpg',
    label: 'Custom Cake 12 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 2000 + 13,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-13.jpg',
    label: 'Custom Cake 13 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 14,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-14.jpg',
    label: 'Custom Cake 14 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 15,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-15.jpg',
    label: 'Custom Cake 15 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 2000 + 16,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-16.jpg',
    label: 'Custom Cake 16 (4:3 Landscape)',
    colSpan: 2,
    rowSpan: 1,
    aspectDesc: '4:3 Landscape',
  },
  {
    id: 2000 + 17,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-17.jpg',
    label: 'Custom Cake 17 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
  {
    id: 2000 + 18,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-18.jpg',
    label: 'Custom Cake 18 (1:1 Square)',
    colSpan: 1,
    rowSpan: 1,
    aspectDesc: '1:1 Square',
  },
  {
    id: 2000 + 19,
    category: 'Custom Cakes',
    image: '/gallery/custom-cakes/custom-cake-19.jpg',
    label: 'Custom Cake 19 (2:3 Portrait)',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Portrait',
  },
];


/* ═══════════════════════════════════════════
   EXCLUSIVE PROMOTIONAL POSTERS & ADS (49 items)
   ═══════════════════════════════════════════ */
const promotionalPosters: GalleryItem[] = [
  {
    id: 5000 + 1,
    category: 'Promotional Posters',
    image: '/ads/soya-chips-savoury-snack-poster.webp',
    label: 'Soya Chips Savoury Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 2,
    category: 'Promotional Posters',
    image: '/ads/namak-para-mathi-snack-poster.webp',
    label: 'Namak Para Savoury Mathi',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 3,
    category: 'Promotional Posters',
    image: '/ads/eggless-coconut-cookies-poster.webp',
    label: 'Eggless Coconut Cookies',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 4,
    category: 'Promotional Posters',
    image: '/ads/potato-puffs-chips-poster.webp',
    label: 'Potato Puffs Savoury Chips',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 5,
    category: 'Promotional Posters',
    image: '/ads/chana-chips-masala-snack-poster.webp',
    label: 'Chana Chips Masala Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 6,
    category: 'Promotional Posters',
    image: '/ads/corn-wafers-crisp-snack-poster.webp',
    label: 'Corn Wafers Crisp Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 7,
    category: 'Promotional Posters',
    image: '/ads/disco-papad-savoury-snack-poster.webp',
    label: 'Disco Papad Savoury Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 8,
    category: 'Promotional Posters',
    image: '/ads/plain-tea-cake-poster.webp',
    label: 'Plain Bakery Tea Cake',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 9,
    category: 'Promotional Posters',
    image: '/ads/savoury-herb-loaf-poster.webp',
    label: 'Savoury Herb Loaf Bread',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 10,
    category: 'Promotional Posters',
    image: '/ads/crispy-mathi-bites-snack-poster.webp',
    label: 'Crispy Mathi Savoury Bites',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 11,
    category: 'Promotional Posters',
    image: '/ads/karela-mathi-savoury-poster.webp',
    label: 'Karela Mathi Savoury',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 12,
    category: 'Promotional Posters',
    image: '/ads/palak-marori-savoury-pastry-poster.webp',
    label: 'Palak Marori Savoury Pastry',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 13,
    category: 'Promotional Posters',
    image: '/ads/patila-puri-crisp-snack-poster.webp',
    label: 'Patila Puri Crisp Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 14,
    category: 'Promotional Posters',
    image: '/ads/motichoor-besan-laddu-poster.webp',
    label: 'Desi Ghee Motichoor Laddu',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 15,
    category: 'Promotional Posters',
    image: '/ads/onion-ring-masala-snack-poster.webp',
    label: 'Onion Ring Masala Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 16,
    category: 'Promotional Posters',
    image: '/ads/eggless-chocolate-cake-poster.webp',
    label: 'Eggless Rich Chocolate Cake',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 17,
    category: 'Promotional Posters',
    image: '/ads/twisty-puff-straws-poster.webp',
    label: 'Twisty Puff Savoury Straws',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 18,
    category: 'Promotional Posters',
    image: '/ads/masala-loaf-bread-poster.webp',
    label: 'Masala Savoury Loaf Bread',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 19,
    category: 'Promotional Posters',
    image: '/ads/eggless-butterscotch-cake-poster.webp',
    label: 'Eggless Butterscotch Cake',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 20,
    category: 'Promotional Posters',
    image: '/ads/chocolate-muffin-delight-poster.webp',
    label: 'Eggless Chocolate Muffin',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 21,
    category: 'Promotional Posters',
    image: '/ads/oregano-savoury-puff-poster.webp',
    label: 'Oregano Savoury Puff',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 22,
    category: 'Promotional Posters',
    image: '/ads/chana-jor-garam-snack-poster.webp',
    label: 'Chana Jor Garam Savoury Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 23,
    category: 'Promotional Posters',
    image: '/ads/diet-snacks-chips-poster.webp',
    label: 'Diet Snack Crispy Chips',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 24,
    category: 'Promotional Posters',
    image: '/ads/methi-thepla-flatbread-poster.webp',
    label: 'Methi Thepla Savoury Flatbread',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 25,
    category: 'Promotional Posters',
    image: '/ads/eggless-pineapple-pastry-poster.webp',
    label: 'Eggless Pineapple Pastry Cake',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 26,
    category: 'Promotional Posters',
    image: '/ads/chinese-samosa-savoury-snack-poster.webp',
    label: 'Chinese Mini Samosa Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 27,
    category: 'Promotional Posters',
    image: '/ads/garlic-cheese-bread-poster.webp',
    label: 'Garlic Cheese Savoury Bread',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 28,
    category: 'Promotional Posters',
    image: '/ads/fluffy-puff-pastry-roll-poster.webp',
    label: 'Fluffy Cream Puff Pastry',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 29,
    category: 'Promotional Posters',
    image: '/ads/chocolate-croissant-poster.webp',
    label: 'Artisan Chocolate Croissant',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 30,
    category: 'Promotional Posters',
    image: '/ads/eggless-fruit-cake-slice-poster.webp',
    label: 'Eggless Fruit Cake Slice',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 31,
    category: 'Promotional Posters',
    image: '/ads/kasuri-methi-mathi-snack-poster.webp',
    label: 'Kasuri Methi Mathi Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 32,
    category: 'Promotional Posters',
    image: '/ads/crunchy-munchy-savoury-crackers-poster.webp',
    label: 'Crunchy Munchy Savoury Crackers',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 33,
    category: 'Promotional Posters',
    image: '/ads/gol-gappa-suji-snack-poster.webp',
    label: 'Gol Gappa Suji Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 34,
    category: 'Promotional Posters',
    image: '/ads/round-fruit-celebration-cake-poster.webp',
    label: 'Round Fruit Celebration Cake',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 35,
    category: 'Promotional Posters',
    image: '/ads/khakhra-plain-savoury-poster.webp',
    label: 'Khakhra Plain Savoury Crisp',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 36,
    category: 'Promotional Posters',
    image: '/ads/puff-square-savoury-bite-poster.webp',
    label: 'Puff Square Savoury Bite',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 37,
    category: 'Promotional Posters',
    image: '/ads/golden-sweet-bun-poster.webp',
    label: 'Golden Sweet Bakery Bun',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 38,
    category: 'Promotional Posters',
    image: '/ads/chakli-masala-spiral-snack-poster.webp',
    label: 'Chakli Masala Spiral Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 39,
    category: 'Promotional Posters',
    image: '/ads/kaju-chips-savoury-delight-poster.webp',
    label: 'Kaju Chips Savoury Delight',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 40,
    category: 'Promotional Posters',
    image: '/ads/cornflakes-dry-fruit-cookies-poster.webp',
    label: 'Cornflakes Dry Fruit Cookies',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 41,
    category: 'Promotional Posters',
    image: '/ads/soya-stick-masala-snack-poster.webp',
    label: 'Soya Stick Masala Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 42,
    category: 'Promotional Posters',
    image: '/ads/tikoni-mathi-flaky-snack-poster.webp',
    label: 'Tikoni Mathi Flaky Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 43,
    category: 'Promotional Posters',
    image: '/ads/crispy-coconut-cookies-classic-poster.webp',
    label: 'Crispy Coconut Cookies Classic',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 44,
    category: 'Promotional Posters',
    image: '/ads/soya-chips-peri-peri-snack-poster.webp',
    label: 'Soya Chips Peri Peri Snack',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 45,
    category: 'Promotional Posters',
    image: '/ads/classic-fruit-cake-poster.webp',
    label: 'Classic Fruit Loaf Cake',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 46,
    category: 'Promotional Posters',
    image: '/ads/stuffed-kulcha-savoury-bread-poster.webp',
    label: 'Stuffed Savoury Kulcha Bread',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 47,
    category: 'Promotional Posters',
    image: '/ads/beetroot-chips-savoury-poster.webp',
    label: 'Beetroot Vegetable Savoury Chips',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 48,
    category: 'Promotional Posters',
    image: '/ads/corn-jor-masala-namkeen-poster.webp',
    label: 'Corn Jor Masala Namkeen',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
  {
    id: 5000 + 49,
    category: 'Promotional Posters',
    image: '/ads/masala-focaccia-savoury-bread-poster.webp',
    label: 'Masala Spiced Focaccia Bread',
    colSpan: 1,
    rowSpan: 2,
    aspectDesc: '2:3 Poster'
  },
];

export const allItems: GalleryItem[] = [
  ...promotionalPosters,...brandedBiscuits, ...brandedNamkeen, ...brandedCakes, ...brandedCustomCakes];


